### ISSUE TITLE
Enhancement

### ISSUE THREAD

**Issue by ghost** [Nitro1231/MineFish-V2#2]
+ Enhancement as updating vetsion up to 1.16.1~(I mean, higher)

**Comment by Nitro1231** [comment]
If there is no major change in the main fishing mechanism, MineFish supports all Minecraft version that has a subtitle function, which includes a lower version of 1.16 and upper version of 1.16 as well. If you are experiencing unknown issues, please report with more detailed information, error log, and screenshots.

Thank you.
